# 激活actuator 部分端点
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: info,health,beans
# 数据库配置
spring:
  datasource:
    url: jdbc:mysql://52.81.60.236:30013/bugly?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: manniu2020
    type: com.alibaba.druid.pool.DruidDataSource
  redis:
    host: 52.81.60.236
    port: 31020
    password:
    timeout: 5000
logging:
  config: classpath:log4j2/log4j2-spring-dev.xml
