
apiVersion: v1
kind: Namespace
metadata:
  name: bugly

---

apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJyZWdpc3RyeS5jbi1oYW5nemhvdS5hbGl5dW5jcy5jb20iOnsidXNlcm5hbWUiOiJidWxseXVuQGFsaXl1bi5jb20iLCJwYXNzd29yZCI6IkRtYW5uaXVAIzIwMjAiLCJlbWFpbCI6IndlaWNoYW5neXVAYnVsbHl1bi5jb20iLCJhdXRoIjoiWW5Wc2JIbDFia0JoYkdsNWRXNHVZMjl0T2tSdFlXNXVhWFZBSXpJd01qQT0ifX19
kind: Secret
metadata:
  name: registry-secret
  namespace: bugly
type: kubernetes.io/dockerconfigjson

---

kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    app: bugly-admin
  name: bugly-admin
  namespace: bugly
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bugly-admin
  template:
    metadata:
      labels:
        app: bugly-admin
    spec:
      imagePullSecrets:
      - name: registry-secret
      containers:
      - name: bugly-admin
        #  换成自己的镜像地址
        image: xxxxxxxxxxxxxx
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          protocol: TCP
        env:
        - name: PARAMS
          #  换成自己数据库地址
          value: --spring.datasource.url=jdbc:mysql://xxxxx:3306/bugly?Unicode=true&characterEncoding=UTF-8&connectTimeout=30000&socketTimeout=30000 --spring.datasource.password=xxxxx
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: bullyun.tools.storage
                values: 
                - "true"
                operator: In
---

kind: Service
apiVersion: v1
metadata:
  labels:
    app: bugly-admin
  name: bugly-admin
  namespace: bugly
spec:
#  type: ClusterIP
#  clusterIP: None
#  ports:
#  - port: 8080
#    targetPort: 8080
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30060
  selector:
    app: bugly-admin

